spring:
    devtools:
        restart:
            enabled: true
    datasource:
        url: jdbc:mariadb://34.64.151.20:3306/Movie?useSSL=false&useUnicode=true&characterEncoding=utf8_general_ci
        username: danny9643
        password: danny31
        driver-class-name: org.mariadb.jdbc.Driver
        initialization-mode: always
        hikari:
            maximum-pool-size: 60
            max-lifetime : 300000
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: false
        hibernate:
            ddl-auto: create
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            use-new-id-generator-mappings: true
        properties:
            hibernate:
                show-sql: false
                format_sql: false
                generate_statistics: false
                use_sql_comments: false
                default_batch_fetch_size: 100
                order_inserts: true
                order_updates: true
    jackson:
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
    profiles:
        active: local
    http:
        multipart:
            enabled: true
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace
server:
  port: 3124
  compression:
    enabled: true
custom:
  path:
    upload-images: '/home/habin/upload'